import os
from dotenv import load_dotenv

load_dotenv()

APPWRITE_PROJECT_ID = os.getenv("APPWRITE_PROJECT_ID")
APPWRITE_API_KEY = os.getenv("APPWRITE_API_KEY")
APPWRITE_DATABASE_ID = os.getenv("APPWRITE_DATABASE_ID") # Add this line

# --- Collection IDs ---
APPWRITE_COLLECTION_PRODUCTS_ID = os.getenv("APPWRITE_COLLECTION_PRODUCTS_ID")
APPWRITE_COLLECTION_BATCHES_ID = os.getenv("APPWRITE_COLLECTION_BATCHES_ID")
APPWRITE_COLLECTION_SUPPLIERS_ID = os.getenv("APPWRITE_COLLECTION_SUPPLIERS_ID")
APPWRITE_COLLECTION_PURCHASE_ORDERS_ID = os.getenv("APPWRITE_COLLECTION_PURCHASE_ORDERS_ID")
APPWRITE_COLLECTION_SALES_ORDERS_ID = os.getenv("APPWRITE_COLLECTION_SALES_ORDERS_ID")
APPWRITE_COLLECTION_CUSTOMERS_ID = os.getenv("APPWRITE_COLLECTION_CUSTOMERS_ID")
APPWRITE_COLLECTION_CUSTOMER_TRANSACTIONS_ID = os.getenv("APPWRITE_COLLECTION_CUSTOMER_TRANSACTIONS_ID")
APPWRITE_COLLECTION_OPERATING_COSTS_ID = os.getenv("APPWRITE_COLLECTION_OPERATING_COSTS_ID")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", "a_very_secret_key_for_development")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 1500